import React, { useRef, useState } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { useEduStore } from './eduStore';
import { Html } from '@react-three/drei';

export function GeographyPlanet() {
  const setSelectedObject = useEduStore(state => state.setSelectedObject);
  const discoverObject = useEduStore(state => state.discoverObject);

  const globeRef = useRef<THREE.Group>(null);
  const [rotationActive, setRotationActive] = useState(true);

  // Focus features
  const [activeFeatureIdx, setActiveFeatureIdx] = useState(0);

  const geographyFeatures = [
    { id: 'mariana_trench', name: 'Mariana Trench', depth: '10,994 meters', desc: 'The deepest oceanic trench on Earth, situated in the western Pacific Ocean. The pressure at the bottom is over 1,000 times the atmospheric pressure at sea level!', funFact: 'If you dropped Mount Everest into the Mariana Trench, its peak would still be covered by more than 2 kilometers of water!' },
    { id: 'tectonic_plates', name: 'San Andreas Fault Line', depth: 'Tectonic Plate Boundary', desc: 'A major continental transform fault extending roughly 1,200 km through California, forming the tectonic boundary between the Pacific Plate and the North American Plate.', funFact: 'The Pacific Plate is moving northwest past the North American Plate at a speed of about 5 centimeters per year—roughly the same speed that human fingernails grow!' },
    { id: 'magma_core', name: 'Earth Outer Core', depth: '2,200 km thick', desc: 'A fluid layer composed of mostly iron and nickel, lying above Earth\'s solid inner core and below its mantle, generating Earth\'s vital protective geomagnetic field.', funFact: 'Without the magnetic field generated by the fluid outer core, solar winds would slowly strip away Earth\'s atmosphere, making the planet completely uninhabitable!' }
  ];

  const currentFeature = geographyFeatures[activeFeatureIdx];

  const geographyFacts = {
    id: currentFeature.id,
    name: `${currentFeature.name} (${currentFeature.depth})`,
    category: 'Physical Geography',
    description: currentFeature.desc,
    funFact: currentFeature.funFact
  };

  useFrame((state) => {
    if (globeRef.current && rotationActive) {
      globeRef.current.rotation.y = state.clock.getElapsedTime() * 0.25;
    }
  });

  const selectFeature = (idx: number) => {
    setActiveFeatureIdx(idx);
    discoverObject(geographyFeatures[idx].id);
  };

  const handleScanFeature = () => {
    setSelectedObject(geographyFacts);
  };

  return (
    <group position={[0, 0, 0]}>
      {/* Geography lights */}
      <pointLight position={[-10, 10, -5]} intensity={1.5} color="#06b6d4" />
      <pointLight position={[10, 10, 5]} intensity={1.5} color="#22d3ee" />

      {/* Grid Floor */}
      <gridHelper args={[12, 12, '#06b6d4', '#083344']} position={[0, 0.01, 0]} />

      {/* --- SPINNING PLANET GLOBE --- */}
      <group position={[0, 1, -1.8]} ref={globeRef}>
        {/* Main ocean sphere base */}
        <mesh onClick={handleScanFeature}>
          <sphereGeometry args={[1.3, 32, 32]} />
          <meshStandardMaterial 
            color="#0284c7" 
            roughness={0.2} 
            metalness={0.3} 
          />
        </mesh>

        {/* 3D Continents representation (Represented as green abstract boxes/shapes bound to sphere) */}
        {/* Americas continent */}
        <mesh position={[-0.8, 0.4, 0.8]} rotation={[0.4, 0.2, -0.4]}>
          <boxGeometry args={[0.5, 0.9, 0.4]} />
          <meshStandardMaterial color="#22c55e" roughness={0.9} />
        </mesh>
        {/* Africa continent */}
        <mesh position={[0.7, -0.2, 0.9]} rotation={[-0.2, 0.6, 0.1]}>
          <boxGeometry args={[0.6, 0.8, 0.5]} />
          <meshStandardMaterial color="#16a34a" roughness={0.9} />
        </mesh>
        {/* Eurasia continent */}
        <mesh position={[0.4, 0.7, -0.5]} rotation={[0.5, -0.3, 0.3]}>
          <boxGeometry args={[1.1, 0.7, 0.6]} />
          <meshStandardMaterial color="#22c55e" roughness={0.9} />
        </mesh>

        {/* Glowing seismic plates boundaries (holographic rings around the globe) */}
        <mesh rotation={[0.5, 0.5, 0.5]}>
          <torusGeometry args={[1.38, 0.012, 8, 48]} />
          <meshBasicMaterial color="#ef4444" transparent opacity={0.3} />
        </mesh>

        {/* Floating Active Feature Target Tag */}
        <Html distanceFactor={8} position={[0, 1.6, 0]} center>
          <div className="bg-zinc-950/95 border border-cyan-400/40 px-3 py-1.5 rounded-2xl text-[8px] font-black uppercase text-cyan-300 tracking-wider whitespace-nowrap shadow-2xl flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />
            🌍 Active Plate: {currentFeature.name}
          </div>
        </Html>
      </group>

      {/* Geography Planet Controller Panel UI */}
      <Html position={[-1.5, 1.8, 1.2]} center distanceFactor={10}>
        <div className="bg-zinc-950/90 border border-cyan-500/30 p-5 rounded-3xl w-60 flex flex-col gap-4 shadow-2xl backdrop-blur-xl pointer-events-auto select-none">
          <div className="border-b border-white/10 pb-2">
            <h4 className="text-xs font-black text-white uppercase tracking-wider">Plate Tectonics</h4>
            <p className="text-[8px] font-bold text-cyan-400 uppercase">Seismic & topographic scan</p>
          </div>

          <div className="flex flex-col gap-2">
            <span className="text-[8px] font-black text-zinc-500 uppercase">Select Planetary Anchor</span>
            <div className="flex flex-col gap-1.5">
              {geographyFeatures.map((feat, idx) => {
                const active = activeFeatureIdx === idx;
                return (
                  <button
                    key={feat.id}
                    onClick={() => selectFeature(idx)}
                    className={`px-3 py-2 rounded-xl text-left text-[9px] font-black uppercase tracking-wider transition-all border flex justify-between items-center ${
                      active
                        ? 'bg-cyan-600 text-white border-cyan-400 shadow-[0_0_10px_rgba(6,182,212,0.3)]'
                        : 'bg-white/5 text-zinc-400 border-white/5 hover:border-white/10'
                    }`}
                  >
                    <span>{feat.name}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="flex flex-col gap-2.5">
            <span className="text-[8px] font-black text-zinc-500 uppercase">Globe Rotation</span>
            <button
              onClick={() => setRotationActive(!rotationActive)}
              className={`w-full py-2 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all ${
                rotationActive
                  ? 'bg-emerald-500/15 border-emerald-400/40 text-emerald-400'
                  : 'bg-zinc-800 border-white/5 text-zinc-500'
              }`}
            >
              {rotationActive ? '🔄 Auto Orbiting ON' : '⏸ Auto Orbiting PAUSED'}
            </button>
          </div>

          <button
            onClick={handleScanFeature}
            className="w-full bg-cyan-500 text-black font-black text-[9px] uppercase tracking-widest py-2 rounded-xl hover:bg-white transition-all cursor-pointer shadow-[0_0_15px_rgba(6,182,212,0.2)]"
          >
            🗺 RUN GEOMAGNETIC SCAN
          </button>
        </div>
      </Html>
    </group>
  );
}
